const Routes = {
  currentUser: (expand = []) => (`/current_user?expand=${expand.join(',')}`),
  dealCategory: (dealId, categoryId, expand = []) => (`/deals/${dealId}/categories/${categoryId}?expand=${expand.join(',')}`),
  dealCategoryExport: (dealId, categoryId, expand = [])  => (`/deals/${dealId}/categories/${categoryId}/export?expand=${expand.join(',')}`),
  dealCategoryTreeElement: (dealId, categoryId, treeElementId, expand = []) => (`/deals/${dealId}/categories/${categoryId}/tree_elements/${treeElementId}?expand=${expand.join(',')}`),
  dealCategoryTreeElementAttachment: (dealId, categoryId, treeElementId, attachmentId, expand = []) => (`/deals/${dealId}/categories/${categoryId}/tree_elements/${treeElementId}/attachments/${attachmentId}?expand=${expand.join(',')}`),
  dealCategoryTreeElementAttachments: (dealId, categoryId, treeElementId, expand = []) => (`/deals/${dealId}/categories/${categoryId}/tree_elements/${treeElementId}/attachments?expand=${expand.join(',')}`),
  dealCategoryTreeElementImanage10Attachments: (dealId, categoryId, treeElementId, expand = []) => (`/deals/${dealId}/categories/${categoryId}/tree_elements/${treeElementId}/imanage10/attachments?expand=${expand.join(',')}`),
  dealCategoryTreeElementNetDocumentsAttachments: (dealId, categoryId, treeElementId, expand = []) => (`/deals/${dealId}/categories/${categoryId}/tree_elements/${treeElementId}/net_documents/attachments?expand=${expand.join(',')}`),
  dealCategoryTreeElementSeeUnityImanageAttachments: (dealId, categoryId, treeElementId, expand = []) => (`/deals/${dealId}/categories/${categoryId}/tree_elements/${treeElementId}/see_unity_imanage/attachments?expand=${expand.join(',')}`),
  dealCategoryTreeElementAttachmentVersion: (dealId, categoryId, treeElementId, attachmentId, versionId, expand = []) => (`/deals/${dealId}/categories/${categoryId}/tree_elements/${treeElementId}/attachments/${attachmentId}/versions/${versionId}?expand=${expand.join(',')}`),
  dealCategoryTreeElementAttachmentVersionDownload: (dealId, categoryId, treeElementId, attachmentId, versionId) => (`/deals/${dealId}/categories/${categoryId}/tree_elements/${treeElementId}/attachments/${attachmentId}/versions/${versionId}/download`),
  dealCategoryTreeElementAttachmentVersionView: (dealId, categoryId, treeElementId, attachmentId, versionId) => (`/deals/${dealId}/categories/${categoryId}/tree_elements/${treeElementId}/attachments/${attachmentId}/versions/${versionId}/view`),
  dealCategoryTreeElementAttachmentVersionSendToDms: (dealId, categoryId, treeElementId, attachmentId, versionId, saveAsType, documentId, documentName = '', destination='', versionDmsId='', comment='', expand = []) => (`/deals/${dealId}/categories/${categoryId}/tree_elements/${treeElementId}/attachments/${attachmentId}/versions/${versionId}/send_to_dms?save_as_type=${saveAsType}&document_id=${documentId}&document_name=${documentName}&destination=${destination}&version_dms_id=${versionDmsId}&comment=${comment}&expand=${expand.join(',')}`),
  dealCategoryTreeElementAttachmentVersionSyncThumbnails:(dealId, categoryId, treeElementId, attachmentId, versionId) => (`/deals/${dealId}/categories/${categoryId}/tree_elements/${treeElementId}/attachments/${attachmentId}/versions/${versionId}/sync_thumbnails`),
  dealCategoryTreeElementAttachmentVersions: (dealId, categoryId, treeElementId, attachmentId, expand = []) => (`/deals/${dealId}/categories/${categoryId}/tree_elements/${treeElementId}/attachments/${attachmentId}/versions?expand=${expand.join(',')}`),
  dealCategoryTreeElementImanage10AttachmentVersions: (dealId, categoryId, treeElementId, attachmentId, expand = []) => (`/deals/${dealId}/categories/${categoryId}/tree_elements/${treeElementId}/imanage10/attachments/${attachmentId}/versions?expand=${expand.join(',')}`),
  dealCategoryTreeElementNetDocumentsAttachmentVersions: (dealId, categoryId, treeElementId, attachmentId, expand = []) => (`/deals/${dealId}/categories/${categoryId}/tree_elements/${treeElementId}/net_documents/attachments/${attachmentId}/versions?expand=${expand.join(',')}`),
  dealCategoryTreeElementSeeUnityImanageAttachmentVersions: (dealId, categoryId, treeElementId, attachmentId, expand = []) => (`/deals/${dealId}/categories/${categoryId}/tree_elements/${treeElementId}/see_unity_imanage/attachments/${attachmentId}/versions?expand=${expand.join(',')}`),
  dealCategoryTreeElementCompletionStatuses: (dealId, categoryId, treeElementId, expand = []) => (`/deals/${dealId}/categories/${categoryId}/tree_elements/${treeElementId}/completion_statuses?expand=${expand.join(',')}`),
  dealCategoryTreeElementCompletionStatus: (dealId, categoryId, treeElementId, completionStatusId, expand = []) => (`/deals/${dealId}/categories/${categoryId}/tree_elements/${treeElementId}/completion_statuses/${completionStatusId}?expand=${expand.join(',')}`),
  dealCategoryTreeElementNotes: (dealId, categoryId, treeElementId, expand = []) => (`/deals/${dealId}/categories/${categoryId}/tree_elements/${treeElementId}/notes?expand=${expand.join(',')}`),
  dealCategoryTreeElementNote: (dealId, categoryId, treeElementId, noteId, expand = []) => (`/deals/${dealId}/categories/${categoryId}/tree_elements/${treeElementId}/notes/${noteId}?expand=${expand.join(',')}`),
  dealCategoryTreeElementResponsibleParties: (dealId, categoryId, treeElementId, expand = []) => (`/deals/${dealId}/categories/${categoryId}/tree_elements/${treeElementId}/responsible_parties?expand=${expand.join(',')}`),
  dealCategoryTreeElementResponsibleParty: (dealId, categoryId, treeElementId, responsiblePartyId, expand = []) => (`/deals/${dealId}/categories/${categoryId}/tree_elements/${treeElementId}/responsible_parties/${responsiblePartyId}?expand=${expand.join(',')}`),
  dealCategoryTreeElementPropagateRestrictionsToDescendants: (dealId, categoryId, treeElementId, expand = []) => (`/deals/${dealId}/categories/${categoryId}/tree_elements/${treeElementId}/propagate_restrictions_to_descendants?expand=${expand.join(',')}`),
  dealCategoryTreeElementRestrictions: (dealId, categoryId, treeElementId, expand = []) => (`/deals/${dealId}/categories/${categoryId}/tree_elements/${treeElementId}/tree_element_restrictions?expand=${expand.join(',')}`),
  dealCategoryTreeElementRestriction: (dealId, categoryId, treeElementId, restrictionId, expand = []) => (`/deals/${dealId}/categories/${categoryId}/tree_elements/${treeElementId}/tree_element_restrictions/${restrictionId}?expand=${expand.join(',')}`),
  dealCategoryTreeElementToDos: (dealId, categoryId, treeElementId, expand = []) => (`/deals/${dealId}/categories/${categoryId}/tree_elements/${treeElementId}/to_dos?expand=${expand.join(',')}`),
  dealCategoryTreeElementToDo: (dealId, categoryId, treeElementId, toDoId, expand = []) => (`/deals/${dealId}/categories/${categoryId}/tree_elements/${treeElementId}/to_dos/${toDoId}?expand=${expand.join(',')}`),
  dealCategoryTreeElements: (dealId, categoryId, expand = []) => (`/deals/${dealId}/categories/${categoryId}/tree_elements?expand=${expand.join(',')}`),
  dealCategoryTreeElementsCreateFromUpload: (dealId, categoryId, expand = []) => (`/deals/${dealId}/categories/${categoryId}/tree_elements/create_from_upload?expand=${expand.join(',')}`),
  dealCategoryVersions: (dealId, categoryId, expand = []) => (`/deals/${dealId}/categories/${categoryId}/versions?expand=${expand.join(',')}`),
  dealClosingBook: (dealId, closingBookId, expand = []) => (`/deals/${dealId}/closing_books/${closingBookId}?expand=${expand.join(',')}`),
  dealClosingBookDownload: (dealId, closingBookId, expand = []) => (`/deals/${dealId}/closing_books/${closingBookId}/download?expand=${expand.join(',')}`),
  dealClosingBooks: (dealId, expand = []) => (`/deals/${dealId}/closing_books?expand=${expand.join(',')}`),
  dealClosingChecklist: (dealId, expand = []) => (`/deals/${dealId}/closing_checklist?expand=${expand.join(',')}`),
  dealCurrentDealEntityUser: (dealId, expand = []) => (`/deals/${dealId}/deal_entity_users/current?expand=${expand.join(',')}`),
  dealDocumentsNotReadyToBeExecuted: (dealId, expand = []) => (`/deals/${dealId}/documents_not_ready_to_be_executed?expand=${expand.join(',')}`),
  dealDocumentsReadyToBeExecuted: (dealId, expand = []) => (`/deals/${dealId}/documents_ready_to_be_executed?expand=${expand.join(',')}`),
  dealDocumentsRequiringThreshold: (dealId, expand = []) => (`/deals/${dealId}/documents_requiring_threshold?expand=${expand.join(',')}`),
  dealProcessDocumentsReadyToBeExecuted: (dealId, expand = []) => (`/deals/${dealId}/process_documents_ready_to_be_executed?expand=${expand.join(',')}`),
  dealRoles: (dealId, expand = []) => (`/deals/${dealId}/roles?expand=${expand.join(',')}`),
  
  dealSignatureGroups: (dealId, expand = []) => (`/deals/${dealId}/signature_groups?expand=${expand.join(',')}`),
  dealSignatureGroup: (dealId, signatureGroupId, expand = []) => (`/deals/${dealId}/signature_groups/${signatureGroupId}?expand=${expand.join(',')}`),
  dealSignatureGroupsBlockCollections: (dealId, signatureGroupId, expand= []) => (`/deals/${dealId}/signature_groups/${signatureGroupId}/block_collections?expand=${expand.join(',')}`),
  dealSignatureGroupsBlockCollection: (dealId, signatureGroupId, blockCollectionId, expand= []) => (`/deals/${dealId}/signature_groups/${signatureGroupId}/block_collections/${blockCollectionId}?expand=${expand.join(',')}`),
  dealSignatureGroupBlockCollectionsLinkBlocks: (dealId, signatureGroupId, expand = []) => (`/deals/${dealId}/signature_groups/${signatureGroupId}/block_collections/link_blocks?expand=${expand.join(',')}`),
  dealSignatureGroupBlockCollectionsUnlinkBlocks: (dealId, signatureGroupId, expand = []) => (`/deals/${dealId}/signature_groups/${signatureGroupId}/block_collections/unlink_blocks?expand=${expand.join(',')}`),
  dealSignatureGroupBlockCollectionSignatureEntity: (dealId, signatureGroupId, blockCollectionId, signatureEntityId, expand= []) => (`/deals/${dealId}/signature_groups/${signatureGroupId}/block_collections/${blockCollectionId}/signature_entities/${signatureEntityId}?expand=${expand.join(',')}`),
  dealSignatureGroupBlockCollectionSigningCapacity: (dealId, signatureGroupId, blockCollectionId, signingCapacityId, expand= []) => (`/deals/${dealId}/signature_groups/${signatureGroupId}/block_collections/${blockCollectionId}/signing_capacities/${signingCapacityId}?expand=${expand.join(',')}`),
  dealSignaturePackets: (dealId, expand = []) => (`/deals/${dealId}/signature_packets?expand=${expand.join(',')}`),
  dealSigner: (dealId, userId, expand = []) => (`/deals/${dealId}/signers/${userId}?expand=${expand.join(',')}`),
  dealSigners: (dealId, expand = []) => (`/deals/${dealId}/signers?expand=${expand.join(',')}`),
  dealSignaturePagesReadyToSend: (dealId, userId, expand = []) => (`/deals/${dealId}/signature_pages/ready_to_send?user_id=${userId}&expand=${expand.join(',')}`),
  dealUnmatchedSignatureUploadRemove: (dealId, unmatchedSignatureUploadId, expand = []) => (`/deals/${dealId}/unmatched_signature_uploads/${unmatchedSignatureUploadId}/remove?expand=${expand.join(',')}`),
  dealUnmatchedSignatureUploadUndoRemoved: (dealId, unmatchedSignatureUploadId, expand = []) => (`/deals/${dealId}/unmatched_signature_uploads/${unmatchedSignatureUploadId}/undo_removed?expand=${expand.join(',')}`),
  dealUnmatchedSignatureUploads: (dealId, expand = []) => (`/deals/${dealId}/unmatched_signature_uploads?expand=${expand.join(',')}`),
  dealUnmatchedSignatureUploadUnmatchedSignaturePageManuallyMatch: (dealId, unmatchedSignatureUploadId, unmatchedSignatureUploadPageId, expand = []) => (`/deals/${dealId}/unmatched_signature_uploads/${unmatchedSignatureUploadId}/unmatched_signature_upload_pages/${unmatchedSignatureUploadPageId}/manually_match?expand=${expand.join(',')}`),
  dealUnmatchedSignatureUploadUnmatchedSignaturePageUndoManuallyMatched: (dealId, unmatchedSignatureUploadId, unmatchedSignatureUploadPageId, expand = []) => (`/deals/${dealId}/unmatched_signature_uploads/${unmatchedSignatureUploadId}/unmatched_signature_upload_pages/${unmatchedSignatureUploadPageId}/undo_manually_matched?expand=${expand.join(',')}`),
  dealVersionDownload: (dealId, versionId) => (`/deals/${dealId}/versions/${versionId}/download`),
  dealVersionView: (dealId, versionId) => (`/deals/${dealId}/versions/${versionId}/view`),
  dealVersion: (dealId, versionId, expand = []) => (`/deals/${dealId}/versions/${versionId}?expand=${expand.join(',')}`),
  dealVersions: (dealId, expand = []) => (`/deals/${dealId}/versions?expand=${expand.join(',')}`),
  dealVotingInterestGroup: (dealId, votingInterestGroupId, expand = []) => (`/deals/${dealId}/voting_interest_groups/${votingInterestGroupId}?expand=${expand.join(',')}`),
  dealVotingInterestGroups: (dealId, expand = []) => (`/deals/${dealId}/voting_interest_groups?expand=${expand.join(',')}`),
  dealVotingInterestGroupVotingInterestThreshold: (dealId, votingInterestGroupId, votingInterestThresholdId, expand = []) => (`/deals/${dealId}/voting_interest_groups/${votingInterestGroupId}/voting_interest_thresholds/${votingInterestThresholdId}?expand=${expand.join(',')}`),
  dealVotingInterestGroupVotingInterestThresholds: (dealId, votingInterestGroupId, expand = []) => (`/deals/${dealId}/voting_interest_groups/${votingInterestGroupId}/voting_interest_thresholds?expand=${expand.join(',')}`),
  imanage10Api: {
    documentWorklist: (dealId) => (`/deals/${dealId}/imanage10/file_picker/documents/document_worklist`),
    folder: (dealId, folderId) => (`/deals/${dealId}/imanage10/file_picker/folders/${folderId}`),
    matterWorklist: (dealId) => (`/deals/${dealId}/imanage10/file_picker/workspaces/matter_worklist`),
    myFavorites: (dealId) => (`/deals/${dealId}/imanage10/file_picker/workspaces/my_favorites`),
    myMatters: (dealId) => (`/deals/${dealId}/imanage10/file_picker/workspaces/my_matters`),
    search: (dealId, query) => (`/deals/${dealId}/imanage10/file_picker/documents/search?query=${query}`),
    versionsList: (dealId, documentId) => (`/deals/${dealId}/imanage10/file_picker/documents/${documentId}/versions_list`),
    workspace: (dealId, workspaceId) => (`/deals/${dealId}/imanage10/file_picker/workspaces/${workspaceId}`)
  },
  moveUnplacedAttachment: (dealId, attachmentId, expand = []) => (`/deals/${dealId}/attachments/${attachmentId}/move_unplaced_attachment?expand=${expand.join(',')}`),
  moveUnplacedVersion: (dealId, versionId, expand = []) => (`/deals/${dealId}/versions/${versionId}/move_unplaced_version?expand=${expand.join(',')}`),
  netDocumentsApi: {
    cabinets: (dealId) => (`/deals/${dealId}/net_documents/file_picker/cabinets`),
    cabinetFolders: (dealId, cabinetId) => (`/deals/${dealId}/net_documents/file_picker/cabinets/${cabinetId}/folders`),
    document: (dealId, documentId) => (`/deals/${dealId}/net_documents/file_picker/documents/${documentId}`),
    folder: (dealId, folderId) => (`/deals/${dealId}/net_documents/file_picker/folders/${folderId}`),
    recentlyAccessedDocuments: (dealId) => (`/deals/${dealId}/net_documents/file_picker/documents/recently_accessed_documents`),
    search: (dealId, query) => (`/deals/${dealId}/net_documents/file_picker/documents/search?query=${query}`),
    workspace: (dealId, workspaceId) => (`/deals/${dealId}/net_documents/file_picker/workspaces/${workspaceId}`),
    workspaces: (dealId, type) => (`/deals/${dealId}/net_documents/file_picker/workspaces?type=${type}`),
  },
  seeUnityImanageApi: {
    documentWorklist: (dealId) => (`/deals/${dealId}/see_unity_imanage/file_picker/documents/document_worklist`),
    folder: (dealId, folderId) => (`/deals/${dealId}/see_unity_imanage/file_picker/folders/${folderId}`),
    matterWorklist: (dealId) => (`/deals/${dealId}/see_unity_imanage/file_picker/workspaces/matter_worklist`),
    myFavorites: (dealId) => (`/deals/${dealId}/see_unity_imanage/file_picker/workspaces/my_favorites`),
    myMatters: (dealId) => (`/deals/${dealId}/see_unity_imanage/file_picker/workspaces/my_matters`),
    search: (dealId, query) => (`/deals/${dealId}/see_unity_imanage/file_picker/documents/search?query=${query}`),
    versionsList: (dealId, documentId) => (`/deals/${dealId}/see_unity_imanage/file_picker/documents/${documentId}/versions_list`),
    document: (dealId, id) => (`/deals/${dealId}/see_unity_imanage/file_picker/documents/${id}`)
  },
  tempUpload: (tempUploadId, expand = []) => (`/temp_uploads/${tempUploadId}?expand=${expand.join(',')}`),
  tempUploadPreview: (tempUploadId, expand = []) => (`/temp_uploads/${tempUploadId}/preview?expand=${expand.join(',')}`),
  tempUploads: (expand = []) => (`/temp_uploads?expand=${expand.join(',')}`),
  tempUploadView: (tempUploadId, expand = []) => (`/temp_uploads/${tempUploadId}/view?expand=${expand.join(',')}`),
  twoFactorAuthenticationDisable: (expand = []) => (`/two_factor_authentication_disable?expand=${expand.join(',')}`),
  twoFactorAuthenticationEnable: (expand = []) => (`/two_factor_authentication_enable?expand=${expand.join(',')}`),
  twoFactorAuthenticationGenerateRecoveryCodes: (expand = []) => (`/two_factor_authentication_generate_recovery_codes?expand=${expand.join(',')}`),
  twoFactorAuthenticationQrCode: (expand = []) => (`/two_factor_authentication_qr_code?expand=${expand.join(',')}`),
  twoFactorAuthenticationVerifyToken: (token, expand = []) => (`/two_factor_authentication_verify_token?expand=${expand.join(',')}`),
  entityUsersList: (entityId, expand = []) => (`/entities/${entityId}/entity_users/?expand=${expand.join(',')}`),
  createTeammMembers: (entityId, expand = []) => (`/entities/${entityId}/entity_users/?expand=${expand.join(',')}`),
  entityUserDetails: (entityId, entityUsersId, expand = []) => (`/entities/${entityId}/entity_users/${entityUsersId}/?expand=${expand.join(',')}`),

}
export default Routes

